### ISSUE TITLE
You must enter a number to go through the menu

### ISSUE THREAD

**Issue by peter910921** [Nokorbis/ar-command-signs#1]
Sorry but im not sure how i can do this, i type 7 or 1 or 3 and press enter, it is not working

**Comment by Nokorbis** [comment]
Can you tell me : 
1. What version of the plugin do you use 
2. What version of Spigot do you use ?
3. What other plugins do you use on your server ?

**Comment by peter910921** [comment]
1. 1.4.2
2. I am using the latest craftbukkit-1.10.2-R0.1-SNAPSHOT-latest
3. Casino slots, CS-CoreLib ,EssentialsX , EssentialsXSpawm, Grief Protection, MobCash, Orebfuscator, Permission Ex, ProtocolLib,RankPrefix,titlewelcomemessage,Vault, worldedit

**Comment by Nokorbis** [comment]
I'm currently running some tests right now. Can you try to update the version of the plugin to 1.5.0 ?
https://www.spigotmc.org/resources/command-signs.10512/

**Comment by peter910921** [comment]
Hmm, seems weird. I download the 1.5.0 but when i go in and type in /commandsign version, it still display 1.4.2 and it is still not working.

**Comment by Nokorbis** [comment]
Perhaps my mistake... I often forget to change the version in the command...

**Comment by Nokorbis** [comment]
Okay,
I've tried all of your plugins one by one with Craftbukkit 1.10.2,
it seems it comes from RankPrefix. That plugin change the chat before I can catch it and I don't think I can change this from my side.

**Comment by peter910921** [comment]
Noted and thanks for the effort
