### ISSUE TITLE
Costs on 1.12

### ISSUE THREAD

**Issue by dweSheppard** [Nokorbis/ar-command-signs#12]
I´m using CommandSign version : 1.5.5 and CraftBukkit version git-Spigot-d5dfb24-ed8c725 (MC: 1.12)
If i setup costs for a sign, the player gets nothing withdraw.

Config: https://pastebin.com/Sn52qVzR

**Comment by Nokorbis** [comment]
I have made some tests to be sure.
It is working for me.

Thus I have two questions:
What plugin do you use for your economy ?
Who is the player testing the command sign ? Is it you ? Are you op ? By default, OPs don't pay for the use a command sign.

**Comment by dweSheppard** [comment]
Oh, Sry.
Yes the group have the command sign admin permission.
