### ISSUE TITLE
Trying to setup buy sign for crate keys

### ISSUE THREAD

**Issue by BytedByte** [Nokorbis/ar-command-signs#13]
Hi, first off, amazing work on the plugin. But there's one issue that i have. The placeholders doesnt seem to work.

I have a sign set up that sells crate keys for in game currency. I have it so it executes the command to give the player a key

'/crate key (name) (crate) (amount)'

So in this case i have a crate for spawners but the command isnt executing properly. What i input was this: '/crate key {NAME} spawners 1' but what comes out in chat when clicking it is this: http://i.imgur.com/DzDkkVc.png

It doesnt register the placeholder for some reason. Are there new and updated placeholders or is this a bug? Thanks and keep up the good work

**Comment by Nokorbis** [comment]
Hello !
The placeholder is %player% 
 ;)

**Comment by Nokorbis** [comment]
Sorry, since I was on my phone, I used the wrong symbols...

%player%

**Comment by BytedByte** [comment]
Wow, Thanks for the fast answer.

That placeholder worked, thank you :)

You should update the user guide on github with the placeholders :)

https://github.com/Nokorbis/ar-command-signs/wiki/Custom-messages

**Comment by Nokorbis** [comment]
Oh :o
You are actually referring to the wrong one. That page is for when you want to customize the displayed message to players (in a file of the plugin's folder).

This page is what you were looking for : https://github.com/Nokorbis/ar-command-signs/wiki/Structure-of-a-Command-Block
