### ISSUE TITLE
%player% placeholder doesn|t seem to work.

### ISSUE THREAD

**Issue by CptLancelotWitty** [Nokorbis/ar-command-signs#17]
I am trying to use a commandsign to execute a command from Random Teleport plugin. The command for random tp is /rtp player world.
So when I try to type in this in the command section in edit mode: rtp %player% vanaheim
Then I get the message in chat: ERROR: That player isn|t online!

What am I doing wrong?
I need some help.

**Comment by Nokorbis** [comment]
Do you have anyway to log the player that the command is receiving ?
Seeing what %player% is being translated to can be helpful in this case.

"Error : that player isn't online" isn't a message from my plugin, so it means this is the rtp command that is sending this message to you.
Are you sure of the syntax of the command ?

**Comment by CptLancelotWitty** [comment]
I'll check into if it is the Random TP plugin.

**Comment by KhaarNaj** [comment]
Maybe just try the original plugin format: [player] (instead of %player% )

command is: /rtp [player] [world | this] <biome> (right?)

https://www.spigotmc.org/resources/random-teleport-1-12-2-a-must-for-factions-and-survival-servers.22835/

**Comment by Nokorbis** [comment]
No news from the author, closing the ticket.
