### ISSUE TITLE
"Permissions Needed" not being obeyed?

### ISSUE THREAD

**Issue by mrcoffee1026** [Nokorbis/ar-command-signs#18]
Permissions required for using the sign is now being ignored since 1.6.2

**Comment by Nokorbis** [comment]
Checking that tomorrow as soon as I wake up

**Comment by mrcoffee1026** [comment]
cool, thank you

**Comment by Nokorbis** [comment]
https://www.spigotmc.org/resources/command-signs.10512/update?update=208134
