### ISSUE TITLE
Command signs vanishing.

### ISSUE THREAD

**Issue by bc-hill** [Nokorbis/ar-command-signs#19]
Spigot 1.12.2
Command Signs 1.6.3

I am finding that I can create a command sign, use it successfully, but eventually the command just vanishes.  
The sign is still there, but the command is gone.  
0.json file is still present in /plugins/CommandSigns/CommandBlocks. 
"/commandsign list" says there are no signs.

What other info can I provide?  Thank you.

**Comment by Nokorbis** [comment]
Hello
Have you created the file while the server was online ? 
Have you tried to use the command : **/commandsign load 0** ?

**Comment by bc-hill** [comment]
The sign was created in-game with /commandsign create
After using /commandsign load 0, it works.
However, I have to run the load command every time the server restarts.

**Comment by Nokorbis** [comment]
Do you have any error message in your log files ?

**Comment by bc-hill** [comment]
Here is everything in my log with "sign" in it:

[15:18:45] [Server thread/INFO]: [CommandSigns] Loading CommandSigns v1.6.3
[15:18:55] [Server thread/INFO]: [CommandSigns] Enabling CommandSigns v1.6.3
[15:18:55] [Server thread/INFO]: [CommandSigns] Plugin vault detected
[15:18:55] [Server thread/INFO]: [CommandSigns] Vault economy linked with command signs ! 
[15:18:55] [Server thread/INFO]: [CommandSigns] CommandSigns properly enabled !

**Comment by Nokorbis** [comment]
Do you have the problem with any other sign ?

**Comment by bc-hill** [comment]
I just started using the plugin.  I created another sign, and a button, and both had the same issue.

**Comment by Nokorbis** [comment]
Can you copy/paste here the content of the json file ?

**Comment by bc-hill** [comment]
{
  "id": 0,
  "name": "enter_arena",
  "world": "ServerSpawn",
  "x": -1539,
  "y": 109,
  "z": 712,
  "disabled": false,
  "commands": [
    "/ma join temp"
  ],
  "needed_permissions": [],
  "temporary_permissions": [],
  "price": 0.0,
  "time_before_execution": 0,
  "move_cancel_timer": false,
  "move_reset_timer": false,
  "global_time_between_usages": 0,
  "player_time_between_usages": 0
}

**Comment by Nokorbis** [comment]
What other plugin do you use ?

**Comment by bc-hill** [comment]
AsyncWorldEditInjector, 
FunnyFilter, 
CoreProtect, 
LuckPerms, 
Vehicles, 
Craftconomy3, 
WorldBorder, 
DecoHeads, 
RelaJumpPads, 
AdvancedPortals,
Arconix, 
AsyncWorldEdit, 
VoidGenerator, 
CraftDisplay, 
SimpleAPI, 
Vault, 
OITCRecoding, 
statuecreator, 
Sit, 
WorldEdit, 
CityWorld, 
Essentials, 
BKCommonLib, 
LightCleaner, 
LWC, 
CommandSigns, 
WorldGuard, 
BlockBall, 
MCPainter, 
My_Worlds, 
CraftBook, 
ArmorStandTools, 
MobArena, 
HolographicDisplays, 
SimplePets, 
Citizens, 
Sentinel


All of the sign stuff in Essentials and Craftbook is disabled.
Thank you.

**Comment by Nokorbis** [comment]
I see that your sign is in a world "ServerSpawn", what is the plugin you use to manage multiple worlds ?

**Comment by bc-hill** [comment]
That is My_Worlds.
https://github.com/bergerhealer/MyWorlds

**Comment by Nokorbis** [comment]
Okay, this might come from that.
That plugin may load after mine, thus my plugin cannot find that world when first loading.
I'll try to compile a version specifically for you

**Comment by Nokorbis** [comment]
Can you try the version uploaded here : https://github.com/Nokorbis/ar-command-signs/releases/tag/v1.6.4 and tell me if it works ?

**Comment by bc-hill** [comment]
Thank you.  You are quick!  
I am so far unable to reproduce the problem, with that build.

**Comment by Nokorbis** [comment]
Perfect :)
