### ISSUE TITLE
Player Name

### ISSUE THREAD

**Issue by peter910921** [Nokorbis/ar-command-signs#2]
Hi,

I try to find something like /give {PLAYER} iron_ingot 64. Which means like who ever click on that sign,{PLAYER} will be replace by the player name who click on that sign.

Can that one be done by your plugin?

**Comment by Nokorbis** [comment]
Solution can be found here https://github.com/Nokorbis/ar-command-signs/wiki/Structure-of-a-Command-Block#variablesplaceholders
:)
