### ISSUE TITLE
Command signs timer reset on restart.

### ISSUE THREAD

**Issue by SoraShiunin** [Nokorbis/ar-command-signs#21]
As the title says...Command sign timer reset on restart.

Any way to prevent this or is it an actual issue?

**Comment by Nokorbis** [comment]
Hello !
Yeah; this is a known bug (or rather a feature I first didnt think of)
it's planned, but not for soon I think (don't want to make false promises)

**Comment by Nokorbis** [comment]
Will be available in version 2.0.0 (soon to be released)
