### ISSUE TITLE
Cant find out how to add cool downs

### ISSUE THREAD

**Issue by Paperboypaddy** [Nokorbis/ar-command-signs#23]
Hello, I just got the plugin on my server and its great but I need a Cooldown because if I keep right clicking it it keeps doing the command. I'm using it to buy items and id be a problem if someone bought stuff on accident. How do I add cooldowns if I can?

**Comment by Nokorbis** [comment]
This is in the Timer section.
They are called "Time between usages"

There are two types of cooldowns : Global and Per player.

Assuming you have 2 players : A & B
If you set a "Time between usages" to 5 seconds, it means that if A uses the sign, neither A or B will be able to use the sign for 5 seconds.
If you set a "Time between player usages" to 5 seconds, it means that if A uses the sign, A will not be able to use the sign for 5 seconds, but B will be able to.

**Comment by Paperboypaddy** [comment]
> This is in the Timer section.
> They are called "Time between usages"
> 
> There are two types of cooldowns : Global and Per player.
> 
> Assuming you have 2 players : A & B
> If you set a "Time between usages" to 5 seconds, it means that if A uses the sign, neither A or B will be able to use the sign for 5 seconds.
> If you set a "Time between player usages" to 5 seconds, it means that if A uses the sign, A will not be able to use the sign for 5 seconds, but B will be able to.

The timer section in your wiki is blank. So what's the cmd that I use to do them?

**Comment by Nokorbis** [comment]
When I said "Timer section" I meant in the edition menu.
When you write **/commandsign edit** (or create)
There is a Timer section.

**Comment by Paperboypaddy** [comment]
Oh. Sorry I actually see there's two plugins called CommandSigns. It wasn't working for me cause I had the other one XDD. This one is way better btw.

**Comment by Nokorbis** [comment]
Ah, lot of people make the confusion ! :D
Thanks ;)

**Comment by Paperboypaddy** [comment]
XD Doesn't work if I use the wrong instructions! Im sorta a plugin developer myself and I try to make my plugins unique as possible but its hard these days with all the plugins out there.
