### ISSUE TITLE
One time signs for a player

### ISSUE THREAD

**Issue by SoraShiunin** [Nokorbis/ar-command-signs#25]
Is there a way to create a one time sign(for each player, the sign doesn't disappear)?
 If not then heres a suggestion. : )

**Comment by Nokorbis** [comment]
Hey,
No, this is not possible on a per-player basis right now.
I'll think about it once I'm done restructuring the code :)

**Comment by Nokorbis** [comment]
Will be possible in version 2.0.0 (soon to be released)

**Comment by gahro-nahvah** [comment]
Hello, I have found a way to use single-use command signs on an older version of the plugin. You use dummy permission nodes and permission checks.

Step 1 is to set your group to have a dummy.example permission node so all users using this sign will have it.

Step 2 is to create a sign that needs permission dummy.example to use the sign.

Step 3 is to make your commands run something along the lines of `#lp user %player% permission set dummy.example false` and then proceed with running your desired commands. Upon retrying to use the sign, the user will receive an error telling them they lack the current dummy.example permission.
