### ISSUE TITLE
Sign Permissions (question)

### ISSUE THREAD

**Issue by JBShady** [Nokorbis/ar-command-signs#26]
I've learned how to use this and it's a great plugin but I am having an issue with signs intended to give players items (a 'kit') for a pvp game.

I have the signs set so no perms are required to use, so all default players can use them.

When the default player clicks the sign the commands do not work (because they do not have OP and cannot use /give and /effect, etc- the **vanilla commands**). There are no perms for these commands to give because it's either OP or not OP for the commands. I need to use the vanilla /give command because of all the tags and customization. /i for example I cannot use because it's not as good.

Is there a way to make it so the console or something executes the command and gives the items, instead of the sign inputting the commands through the player when clicked? I am very confused and don't understand why the player needs to be OP in order to use a sign intended to give all players items. Maybe what I am asking is possible, but I'm just doing something wrong.

EDIT: I just realized you could replace the / with # or ^ and this might fix my issue, I apologize for this issue if it all works out.

**Comment by Nokorbis** [comment]
Hello there
Have you tried to add the temporary permission
"minecraft.command.give" ?It should be the permission for vanilla commands

**Comment by JBShady** [comment]
I will try that too. This is my first time ever using permissions and I'm learning so much so please excuse my very limited knowledge lol. Thanks and this is a great plugin!

**Comment by Nokorbis** [comment]
Concerning your edit,
I would discourage the use of ^ (op) and prefer the use of # (server) if you actually need it.
^ actually means the player will be oped during the execution of the command. IF for any reason, the server crashes during this timing, the player will be oped at the restart (which is usually not wanted :D)

Honestly, this should never happen so it's not bad to use it. But this is a fact to know. (Myself, as the developer, I tend to avoid the usage of op (^))

EDIT : However, using the server version (#) involves that the command need a way to send the clicking player (with %player% placeholder) into its parameters

**Comment by JBShady** [comment]
Okay thanks again. I will use #. So just double checking the # will work on any command on the sign? Not just essentials?

**Comment by Nokorbis** [comment]
It works on any command, but it means that the server will be considered as the sender.
this involves that usually, the sending player should be passed as an argument (with %player%) if the command can accept it

**Comment by JBShady** [comment]
Cool, and yeah I am using the %player% placeholder in all my commands. I'll update when I test this later today. Also I'm using the current plugin on a 1.8 spigot server and so far it works perfectly fine but is there a older version you recommend or it should be fine?

**Comment by Nokorbis** [comment]
CommandSigns version 1.6.7 should be fine even though I don't support spigot 1.8 anymore

**Comment by JBShady** [comment]
The # works perfectly and thanks for quick reply + amazing plugin, keep it up.
