### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by SoraShiunin** [Nokorbis/ar-command-signs#29]
I'm not sure how to update. I've followed the migration guide but it doesn't update.
It might be because someone is hosting my server so offline commands don't go through the console.
Is there another way to convert?

**Comment by Nokorbis** [comment]
Hello there.
First, can you explain me exactly what you are doing ?
Note that the Updater does not upgrade the version of the plugin, it only convert data files. Thus you need to upload the new version of the plugin.

**Comment by Nokorbis** [comment]
Additionally, the command should not be entered in the game console, but in the server (linux probably) console.

**Comment by SoraShiunin** [comment]
That is the exact issue. I have no access the servers computer console. Only the servers console when its online.
I imagine this is the same for many other people using hosts.

**Comment by Nokorbis** [comment]
Do you have access to the data files (with an FTP access or something) ?

**Comment by SoraShiunin** [comment]
Yes

**Comment by Nokorbis** [comment]
If you want, you can send me the data files (in /plugins/CommandSigns/CommandBlocks) on the spigot forum and I can make the conversion for you.

**Comment by Nokorbis** [comment]
Keep a copy of these data files in case there is an error

**Comment by SoraShiunin** [comment]
Yes please. Sorry for late reply.
[CommandSigns.zip](https://github.com/Nokorbis/ar-command-signs/files/3194480/CommandSigns.zip)

**Comment by Nokorbis** [comment]
Here are the converted files:
[CommandBlocks.zip](https://github.com/Nokorbis/ar-command-signs/files/3194483/CommandBlocks.zip)
You can put the result in **/plugins/CommandSigns/CommandBlocks**
in a way that you have your json files in 
**/plugins/CommandSigns/CommandBlocks/configurations**
