### ISSUE TITLE
Cooldown message correction

### ISSUE THREAD

**Issue by SlimeDog** [Nokorbis/ar-command-signs#30]
Spigot 1.14.1
CommandSigns 2.1.0

Message is commented out in message.properties. Default message reads in red:
```
You have already used this command block 10.5 seconds seconds ago. You must wait 1 minute 49.5 seconds more seconds.
```
Note that {TIME} and {REMAINING} contains "minutes" and "seconds".

**Comment by Nokorbis** [comment]
Indeed ! 
I noticed it before releasing the not-beta 2.0.0 version.
You can see the fix in the commit https://github.com/Nokorbis/ar-command-signs/commit/24cc61057228426683dd90487ed5a0f5815cca85
You can edit the file yourself (in /messages/addons.lang) (it won't fix itself except if you delete the file at the next update)

**Comment by SlimeDog** [comment]
Already edited. :)
