### ISSUE TITLE
Closing command sign creation without selecting a location causes problems.

### ISSUE THREAD

**Issue by selfslaughter** [Nokorbis/ar-command-signs#31]
Using CommandSigns 2.1.0 on Paper 1.14.2.

Type /commandsign create
Select "done" without selecting a block.
Try to view the broken sign with /commandsign list

Invalid command sign is saved despite having no location data and throws an error if it should appear in /commandsign list.

Error Log - https://pastebin.com/raw/U07VzqP4
Invalid Sign - https://pastebin.com/raw/fwMkc1fp

**Comment by Nokorbis** [comment]
I'll check that after work.
You shouldn't be able to create a command sign without a block selected

**Comment by Nokorbis** [comment]
Fixed in version 2.0.1 (for Spigot 1.13) and 2.1.1 (for Spigot 1.14)

**Comment by selfslaughter** [comment]
Yeap, that certainly stops it. Thanks.

Maybe an option to cancel creation would be nice. But beyond the scope of this ticket :)
