### ISSUE TITLE
Help menu throws errors on erroneous input

### ISSUE THREAD

**Issue by selfslaughter** [Nokorbis/ar-command-signs#32]
Command Signs 2.1.1 on Paper 1.14.2 (Build 55)

Getting anything wrong in the help command throws an unhandled exception.

ie. /ncs help 2

https://pastebin.com/raw/vKgaV7KM

**Comment by Nokorbis** [comment]
It will be fixed in version 2.1.2.
I just wait a little before releasing it in case you find any other error to avoid release 3 version in 3 days :D

**Comment by selfslaughter** [comment]
haha, all good mate.

Just prepping for a possible switch to 1.14.2, so we're doing our best to try and break everything at the moment.  :)
