### ISSUE TITLE
Using the # to perform the command doesn't work

### ISSUE THREAD

**Issue by Davidozs** [Nokorbis/ar-command-signs#34]
Hi,

I am trying to get players to teleport somewhere by using a sign, but it's not working at all, and I've tried everything. I've tried using permissions (minecraft.command.tp), using the # in front of it, changing @s with @p but when I am not an operator I just can't get it to work. Any help would be greatly appriciated.

**Comment by Nokorbis** [comment]
Hello, you should not use @p
In Command Signs, the placeholder for player is **%player%**

**Comment by Davidozs** [comment]
![image](https://user-images.githubusercontent.com/52178206/60129023-5e074700-9794-11e9-8d43-d640f8b2fe1e.png)
Still doesn't work, I have the command put in like this, and in the temporary permissions I have minecraft.command.tp and minecraft.command.teleport because I don't know what one of the two is right, but it still doesn't work. Any clue?

It works when I'm OP, but when I DE-OP myself it doesn't, so it must be something with permissions.

**Comment by Nokorbis** [comment]
What is happening if you remove the "minecraft:" prefix ?

**Comment by Davidozs** [comment]
It still doesn't work.

**Comment by Nokorbis** [comment]
What is the version of spigot and command signs you are using ?
I'll have a better check when I come back from work tonight.

**Comment by Davidozs** [comment]
both is latest, but I think I found the error: Outside of the region I set with worldguard the sign works just fine, but inside it doesn't. So it has something to do with permissions inside the region, but I have absolutaly no clue on how to fix it.

**Comment by Nokorbis** [comment]
When you say it does not work,
do you have an error message ?
If not, try to allow the interact flag in your world guard region.
Else, send me the error message
