### ISSUE TITLE
How can I use the plugin to buy commands permanently? 

### ISSUE THREAD

**Issue by KellyButton** [Nokorbis/ar-command-signs#35]
Hi, I'm having trouble working this plugin to do exactly what I need it to do. I want to have players be able to buy the permission (permanently) to use a certain warp. I've set it up properly to the point that the sign takes the money from the player, but when they try to use the warp, it says they dont have permission. I've also figured out how to make the sign teleport the player to the warp but once they leave, they will no longer be able to warp back unless they pay the sign again. I'm certain the plugin allows me to do what I want but I can't seem to figure out how to do it.

**Comment by Nokorbis** [comment]
Hello,
Command Signs has only one game : Make a block run a Command when you interact with it.
You can't make a sign require money the first time and bypass next time.
However, what you can do, according to you permissions management plugin, 
is to give the permission to warp to a specific location when they use the command sign.
You could do something like (in GroupManager)
#manuaddp %player% essentials.warps
#manuaddp %player% essentials.warp.your_location
This way, they can run the command themselves.

**Comment by KellyButton** [comment]
Ah okay, thanks anyways.
