### ISSUE TITLE
Economy Cost Doesn't Work

### ISSUE THREAD

**Issue by PrinceOfIonia** [Nokorbis/ar-command-signs#37]
Hi there, so here is the issue I am having.

The command runs perfectly fine, but will run even if you cannot pay.

Let's say I have $5 and my 'CommandSign' has a set cost of $10, if I right click my CommandSign the command will be preformed anyways, basically making the cost on the CommandSign useless. It even works if you have negative balance or 0 balance.

It does still subtract currency from your account, but it doesn't actually care how much money you have, so if I click on my CommandSign again with $5 in my balance, I would either end up with $0 (If I disabled debts in Essentials) or just end up with negative balance on my account (For this example it would be -$5).

There are no console errors popping up anywhere.

I am running the latest version of Vault, I am also running the latest version of your plugin.

My Minecraft Server Version is 1.14.3

Could someone help me? Maybe I'm just doing something wrong here, thanks!

**Comment by Nokorbis** [comment]
1) Are you using spigot ?
2) What version of my plugin are you using ?
3) Can you give me the configuration of the sign ?

**Comment by Nokorbis** [comment]
Can you also check that you do not have the permission : commandsign.costs.bypass

**Comment by Nokorbis** [comment]
Other question, when you start your server
Do you have any of the following LOG appearing ?

- Plugin vault detected
- Vault economy linked with command signs !
- No vault economy hooked

**Comment by PrinceOfIonia** [comment]
I'm using spigot, I'm also using the latest version of your plugin. Not sure how to exactly send you my sign config.

In my server start-up, I did see "Plugin vault detected" and "Vault economy linked with command signs !"

**Comment by Nokorbis** [comment]
For the config, 
You can get the id of the sign with the /NCS info command.
Then you can go to your /plugins/command signs/configurations folder.
And send me your <id>.JSON file
(Sorry for cases, on my phone right now)

**Comment by PrinceOfIonia** [comment]
Okay, I got my config, here you go.
[SignConfig.zip](https://github.com/Nokorbis/ar-command-signs/files/3370392/SignConfig.zip)

**Comment by Nokorbis** [comment]
What is the plugin you use for your Economy ?

**Comment by PrinceOfIonia** [comment]
Vault, I have Essentials too.

**Comment by Nokorbis** [comment]
Vault is the only the API, not the implementation.
Weird that Essentials does that. Are you sure it is up to date ?

**Comment by PrinceOfIonia** [comment]
Yes, latest version. Made to run on 1.14.3 Spigot Servers.

**Comment by PrinceOfIonia** [comment]
![image](https://user-images.githubusercontent.com/18065446/60859939-5c04a580-a1e2-11e9-9933-9f8adeca85d2.png)
Just in case, I'll upload an image of my plugins here.

**Comment by Nokorbis** [comment]
I see MMO stuff,
does any of those plugin also have an economy system in it ? Would any of those be the one that actually "pay" the sign ?

**Comment by PrinceOfIonia** [comment]
Nope, just Vault and Essentials. Reminder that I get absolutely no console errors when using your plugin, or any plugin related to this issue for that matter.

**Comment by PrinceOfIonia** [comment]
Are you unable to replicate my issue?

**Comment by PrinceOfIonia** [comment]
Okay, found something new, so it only does this on Admins/OP'd players. Apparently works normal for regular players.

**Comment by Nokorbis** [comment]
If this is only for Admins, this must be because of the "commandsign.costs.bypass" as I mentionned in my second answer

**Comment by PrinceOfIonia** [comment]
My bad, I must've forgotten about that when I saw it, I apologize.
