### ISSUE TITLE
Delete command sign

### ISSUE THREAD

**Issue by mareksipos93** [Nokorbis/ar-command-signs#38]
EDIT: EVERYTHING BELOW IS FALSE POSITIVE
I have been left-clicking signs instead of right-clicking when deleting them ! 
My fault !

Hi, I have a suggestion. (EDIT: and bug report)

Make it possible to delete command signs without manually removing commands first.

So when you use /cmdsign delete ID, it would just delete all commands automatically.

EDIT: so I have deleted all commands of command signs and it still says that it's a command block and I need to remove commands first... 

EDIT2: ok after using /cmdsign copy and clicking on sign it said again that I need to remove commands first for deleting... so it got stuck on deleting.
Restarted server and it worked correctly. There is bug somewhere.

**Comment by Nokorbis** [comment]
I'll check that after work
But that's not supposed to be the meaning of the message (that I'll check too)
What it means, is that the **block** is protected from destruction as long as there is a configuration (at the Command Signs plugin meaning) on it. This is not about commands, this about "anything" :D

/cmdsign delete <ID>
is actually the command to delete "that configuration" and that will make the **block** destroyable.

When you run the command above, you can run it again to confirm the deletion.

Once again, I'll check if there is a bug there after work

**Comment by mareksipos93** [comment]
> I'll check that after work
> But that's not supposed to be the meaning of the message (that I'll check too)
> What it means, is that the **block** is protected from destruction as long as there is a configuration (at the Command Signs plugin meaning) on it. This is not about commands, this about "anything" :D
> 
> /cmdsign delete 
> is actually the command to delete "that configuration" and that will make the **block** destroyable.
> 
> When you run the command above, you can run it again to confirm the deletion.
> 
> Once again, I'll check if there is a bug there after work

I'm so sorry, I have edited previous post too late.

There is no bug, it's just my fault. I was left-clicking all the time, not right-clicking.

**Comment by Nokorbis** [comment]
> 
> 
> > I'll check that after work
> > But that's not supposed to be the meaning of the message (that I'll check too)
> > What it means, is that the **block** is protected from destruction as long as there is a configuration (at the Command Signs plugin meaning) on it. This is not about commands, this about "anything" :D
> > /cmdsign delete
> > is actually the command to delete "that configuration" and that will make the **block** destroyable.
> > When you run the command above, you can run it again to confirm the deletion.
> > Once again, I'll check if there is a bug there after work
> 
> I'm so sorry, I have edited previous post too late.
> 
> There is no bug, it's just my fault. I was left-clicking all the time, not right-clicking.

Then can you edit or post a new message with only what you think is a bug and without what isn't ? :D
I'm a bit confused with your first post ^^'

**Comment by mareksipos93** [comment]
Yeah I have confused myself as well. Sorry for that. Everything works correctly.

**Comment by Nokorbis** [comment]
Okay, cool then :)
