### ISSUE TITLE
Disabling auto-removal ?

### ISSUE THREAD

**Issue by mareksipos93** [Nokorbis/ar-command-signs#39]
Hello,

is there any way how to disable automatic command sign removal?

I have custom world which gets loaded on first try to access it (to save resources) and I want to use command signs in that world. But on every restart all command signs get removed, because that world is not loaded at the time.

Thank you

**Comment by Nokorbis** [comment]
You mean the configuration files are deleted ?

**Comment by mareksipos93** [comment]
No, command sign gets deleted.

Its not in /cmds list anymore.

**Comment by Nokorbis** [comment]
Once the world is loaded, what happens when you do **/cmds reload** ?

**Comment by mareksipos93** [comment]
> Once the world is loaded, what happens when you do **/cmds reload** ?

Wow that works! Signs are in list now.

So maybe I would suggest listening to world loading event and loading signs for them :)

**Comment by Nokorbis** [comment]
Yeah, that's what I thought :)
Just wanted to be sure

**Comment by Nokorbis** [comment]
I have attempted a fix in the alpha version for 2.1.3
https://github.com/Nokorbis/ar-command-signs/releases/tag/2.1.3.Alpha
