### ISSUE TITLE
Moveable actuators

### ISSUE THREAD

**Issue by SlimeDog** [Nokorbis/ar-command-signs#44]
I have a ARCS actuator (same issue with sign or button) that is part of an elevator. That is, it moves with the elevator. So it can be active at multiple Y-levels (X and Z are constants, obviously). Unfortunately, ARCS disables signs that are not found at server start-up or **arcs reload**. I can work around the issue, in a clumsy sort of way, but I am wondering if there is something that can be added to the plugin design to accommodate this feature.

**Comment by Nokorbis** [comment]
How do you work around the issue ?

**Comment by SlimeDog** [comment]
With redstone and command blocks. When I arrive at one of the Y-levels of interest, I trigger **arcs reload**. Not very elegant.

**Comment by SlimeDog** [comment]
Basically, I want to have the functionality that says: Trust this ARCS location. It's valid, even if it doesn't look like it at this moment.

**Comment by Nokorbis** [comment]
I see what you mean.
With all the work I have, I'm not in the mood to develop at the moment. But I'll consider it

**Comment by SlimeDog** [comment]
Thanks. It would be very much appreciated.

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
