### ISSUE TITLE
Normal player canot use the sign

### ISSUE THREAD

**Issue by DJLukkie** [Nokorbis/ar-command-signs#46]
a normal player with the permissions can't use the sign?

**Comment by Nokorbis** [comment]
What permissions ?

**Comment by Nokorbis** [comment]
What is the version of Spigot you are using ? 
What is the version of Command Signs you are using  ?
What is the configuration of the Command Sign on which you have a problem ? 
What are you trying to do ? 
What is the expected behavior ? 
What is the actual behavior ?
