### ISSUE TITLE
Cant Join the Server if I install CommandSign v2.2.0

### ISSUE THREAD

**Issue by sandboxgamer92** [Nokorbis/ar-command-signs#47]
Hello,

I can't Join my Server, if I install CommandSign v2.2.0.

My Server: Minecraft Spigot 1.15.2

Using: Essentials, PermissionEx, Vault, BKCommonLib-1.15.2, TrainCarts-1.15.2-v1, WorldEdit, WordGard, PlotSquared and AsyncWorldEdit-3.6.19.

I have do nothing on the server. No settings, nothing. Only installing CommandSign and then I can't join the server.

Thank you for help.

**Comment by Nokorbis** [comment]
Hello, do you have logs on your server ?
