### ISSUE TITLE
Only Ops can use signs

### ISSUE THREAD

**Issue by ryanou812** [Nokorbis/ar-command-signs#55]
I feel like I've tried everything but even a simple command like /warp spawn. They permission group has the permission essentials.warps.spawn and essentials.warp and can perform the command without the sign, but when trying to use the command with the sign nothing at all happens. Ops can use the signs perfectly however. I also have tried switching the commands to ^ and # before the command but default users still cannot interact with the signs

**Comment by Nokorbis** [comment]
Do you use worldguard ?
It might be because worldguard prevent the use/interact permission

**Comment by ryanou812** [comment]
i havent created a region in which the sign exists and set interact and use to allow and still nothing happens

**Comment by ryanou812** [comment]
I am using LuckPerms as my permissions plugin if that helps

**Comment by Nokorbis** [comment]
I don't think that it's my plugin preventing your users to use the sign.

My plugin only does :

1. Receive an interact/use event from Bukkit/Spigot (which can be prevented by other plugins)
2. Check if the required permissions set on the sign are on the user (using the Bukkit Permissions API, so if LuckPerms respect that API, no reason it doesn't work)
3. Add temporary permissions
4. Makes the player run the commands
5. Remove temporary permissions

If your users don't see a message in chat when interacting with the sign, only the first point can be in cause. So you should check if you have other protection tools
