### ISSUE TITLE
Help With Enabling Non-Operators to Use Signs

### ISSUE THREAD

**Issue by Qu4ntumEl1xir** [Nokorbis/ar-command-signs#56]
When testing the commandsigns I found that when I deopped myself (because the server isn't open to the public yet) I couldn't use a sign which teleports me to a certain part of my server. If you could help me fix this issue it would be appreciated. Thanks.

**Comment by Nokorbis** [comment]
https://github.com/Nokorbis/ar-command-signs/issues/54
