### ISSUE TITLE
Let a commandsign cost money

### ISSUE THREAD

**Issue by Fantabaum** [Nokorbis/ar-command-signs#58]
**What is the version of Spigot you are using ?**
paper 1.15.2
**What is the version of CommandSigns you are using ?**
newest
**What is your question ?**
i saw in reviews thats its possible to let the use of a command sign cost money, but hows that possible? ive vault and a economy already

**Comment by Nokorbis** [comment]
What is the plugin you are using for your economy ?

**Comment by Nokorbis** [comment]
Do you have those messages when you start your server:

[07:10:58 INFO]: [CommandSigns] Enabling CommandSigns v2.2.0  
[07:10:58 INFO]: [CommandSigns] **Plugin vault detected**  
[07:10:58 INFO]: [CommandSigns] **No vault economy hooked.**

**Comment by Nokorbis** [comment]
First things you should make sure :
- You have an economy plugin (that isn't Vault. Vault isn't really a plugin. It's an API that allows plugins like mine to communicate with economy plugins that support it)
- Your (economy) plugin supports Vault

**Comment by Fantabaum** [comment]
oh sorry forgot how good the menu is and found it by myself now. you can completly delete this issue. Sorry
