### ISSUE TITLE
[1.16.1] Console spam when loading server.

### ISSUE THREAD

**Issue by ShroomAgent27** [Nokorbis/ar-command-signs#59]
**What is your version of Spigot ?**
This server is running Paper version git-Paper-86 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**What is the version of CommandSigns you are using ?**
CommandSigns-2.2.0

**What are you doing ?**
Booting up the server.

**Expected behavior**
Console to not be spammed with error messages.

**Actual behavior**
Console is spammed with error messages.
**Any log ?**
https://pastebin.com/a51JxaYx

**Additional context**
It's really weird, since it seems to some sort of chunk checker, but it only happens when CommandSigns is loaded. If I remove the plugin jar from the plugins folder, nothing happens.

**Comment by Nokorbis** [comment]
That's weird, that is not a message generated by my plugin

**Comment by ShroomAgent27** [comment]
Okay, this seems to be a Mojang issue, actually.

https://bugs.mojang.com/browse/MC-191388

Weird that the console spam didn't happen when your plugin was disabled, but it's not your fault. Hopefully Mojang or someone can get it fixed.
