### ISSUE TITLE
Command Signs causing crashes

### ISSUE THREAD

**Issue by taylorhaight** [Nokorbis/ar-command-signs#60]
Since the 1.16 update my Command Signs have been causing crashes whenever it gets overwhelmed. I've included the logs of the latest crash attached to this as well as the command sign that is most easy to replicate the issue with.
[Crash Log.txt](https://github.com/Nokorbis/ar-command-signs/files/5047942/Crash.Log.txt)
![Screenshot_9](https://user-images.githubusercontent.com/11755568/89736443-05921800-da2f-11ea-9f23-15f6c25c6626.png)
Was wondering if there's something that can be done to remedy this. Thanks in advance.

**Comment by Nokorbis** [comment]
Hello,
I've check, no reason why Command Signs would crash a server.
In your logs, it mentions another plugin that intercept one of my plugin's action (player chatting) : UltimateChat
You should check that plugin.
