### ISSUE TITLE
FOR ALL THE PLAYERS LOOKING FOR EXECUTE COMMANDS

### ISSUE THREAD

**Issue by Espinete1987** [Nokorbis/ar-command-signs#65]
FOR ALL PLAYERS who wanted to use this plugin to execute commands as server

This PLUGIN doesnt work for it
After hours of searching i realiced that this plugin it does even whithout set complicated commands, its damn simple!!
https://www.spigotmc.org/resources/serversigns.10693/

Just need to place a sign, add the command and then a word as a permission if you want. Then add the permission in luckperms or whatever plugin are you using

**Comment by Nokorbis** [comment]
You just need to replace the command prefix ( **/** ) by **#** and the command will be executed by the server console.
